# Generated by Django 2.2.16 on 2022-08-27 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('id',)},
        ),
    ]
